config/routes.rb
QrcodeAdvice::Application.routes.draw do
  resources :points

  resources :products
  match 'p/v/:id' => 'points#visit'

  match 'products/new_code/:id' => 'products#new_code'
  match 'p/v/:id' => 'products#view'
  match 'contacts' => 'home#contacts'
  match 'info' => 'home#info'
  root :to => "points#index"

end

app/models/point.rb
require 'qr_image'
class Point < ActiveRecord::Base

  def before_create
    self.visit_number = 0
  end

  def after_destroy
    File.delete(self.qr_path) if File.exist?(self.qr_path)
  end

  QR_IMAGES_DIR = File.join(RAILS_ROOT, 'public/qr')
  QR_SIZE = 5

  def create_qr_image(request)
    QrImage.create_image(qr_path, qr_text(request), 4, 10, 10)
  end

  def qr_text(request)
    "#{request.protocol}#{request.host}/p/v/#{self.id}"
  end

  def qr_code(request)
    QrImage.get_code(qr_text(request), QR_SIZE)
  end

  def qr_url
    File.join('qr/', "#{self.id}.jpg")
  end

  def qr_path
    File.join(QR_IMAGES_DIR, "#{self.id}.jpg")
  end

  def visit!
    self.visit_number += 1
    self.save
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_download_link
  def set_download_link
    @download_link = 'http://www.upcode.mobi/'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController 

  def index
  end

  def contacts
  end

  def info
  end
  
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  # GET /points
  # GET /points.xml
  def index
    @points = Point.all
    @points = @points.sort {|x,y| y.visit_number <=> x.visit_number } if params[:sort]

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @points }
    end
  end

  # GET /points/1
  # GET /points/1.xml
  def show
    @point = Point.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @point }
    end
  end

  def visit
    @point = Point.find(params[:id])
    @point.visit! if @point
  end

  # GET /points/new
  # GET /points/new.xml
  def new
    @point = Point.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @point }
    end
  end

  # GET /points/1/edit
  def edit
    @point = Point.find(params[:id])
  end

  # POST /points
  # POST /points.xml
  def create
    @point = Point.new(params[:point])

    respond_to do |format|
      if @point.save
        @point.create_qr_image(request)
        format.html { redirect_to(:action => :index) }
        format.xml  { render :xml => @point, :status => :created, :location => @point }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /points/1
  # PUT /points/1.xml
  def update
    @point = Point.find(params[:id])

    respond_to do |format|
      if @point.update_attributes(params[:point])
        format.html { redirect_to(:action => :index) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.xml
  def destroy
    @point = Point.find(params[:id])
    @point.destroy

    respond_to do |format|
      format.html { redirect_to(points_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.xml

  before_filter :authenticate, :except => [:view]
  USERS = { "admin" => "goodgolly" }
  def authenticate
    authenticate_or_request_with_http_digest("Application") do |name|
      USERS[name]
    end
  end

  def list
    @products = Product.all
  end

  def view
    id = params[:id].to_i
    @product = Product.find_by_id(id)
  end

  def new_code
    product = Product.find(params[:id])
    code = product.id
    @cell_sizes = 1..10 
    @code_sizes = 3..10
    if params[:cell_size]
      @cell_size = params[:cell_size].to_i
    else
      params[:cell_size] = 3
      @cell_size = 3
    end
    if params[:code_size]
      @code_size = params[:code_size].to_i
    else
      params[:code_size] = 3
      @code_size = 3
    end
    @qr = RQRCode::QRCode.new("http://tovarid.com/p/v/#{code}",:size => @code_size) 
  end

  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/contacts.html.erb
<b>ТОВ "Вайс Едвайс"</b>
<br/>
<br/>
<table cellpadding="0" cellspacing="0" >
  <tr valign="top" >
    <td style="width:80px;">Телефон</td>
    <td>
      +38 044 362 80 72<br/>
      +38 063 227 59 08
    </td>
  </tr>
  <tr>
    <td>Пошта</td>
    <td>tovarid.com@gmail.com</td>
  </tr>
  <tr>
    <td>Адреса</td>
    <td>м. Київ, п-т Ватутіна 14а, к 30</td>
  </tr>
</table>

app/views/home/index.html.erb
<table id="links_table">
  <tr>
    <td valign="bottom">
      <%= link_to @download_link do %> 
        <%= image_tag('small/download.png') %>
        &nbsp;Завантажити програму
      <% end %>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to '/contacts' do %> 
        <%= image_tag('small/mail.png') %>
        &nbsp;Контакти 
      <% end %>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to '/info' do %> 
        <%= image_tag('small/help.png') %>
        &nbsp;Про проект  
      <% end %>
    </td>
  </tr>
</table>
<br/>
<%= link_to 'адміністрування', :controller => 'products', :action => 'index' %>

app/views/home/info.html.erb
<div style="width:300px;text-align:justify;">&emsp;&emsp;Сервіс <span style="font-size:12pt;">Tovar<span style="color:red;">ID</span></span> створено для максимально точної ідентифікації товарів виробників і уникнення їх підробок.<br/>&emsp; Покупці зможуть відрізняти дійсний товар від підробного за допомогою мобільного телефону та 
  <%= link_to 'спеціального програмного забезпечення', @download_link, :style => "text-decoration:underline;" %>
  .
</div>
<div style="width:425px" id="__ss_5888894">
  <strong style="display:block;margin:12px 0 4px">
    <a href="http://www.slideshare.net/WiseAdviceLtd/tovaridcom" title="TovarID.com">TovarID.com</a>
</strong>
<object id="__sse5888894" width="425" height="355">
  <param name="movie" value="http://static.slidesharecdn.com/swf/ssplayer2.swf?doc=random-101124084409-phpapp01&rel=0&stripped_title=tovaridcom&userName=WiseAdviceLtd" />
  <param name="allowFullScreen" value="true"/>
  <param name="allowScriptAccess" value="always"/>
  <embed name="__sse5888894" src="http://static.slidesharecdn.com/swf/ssplayer2.swf?doc=random-101124084409-phpapp01&rel=0&stripped_title=tovaridcom&userName=WiseAdviceLtd" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="355"></embed></object>

app/views/layouts/_products.html.erb
<%= yield %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TovarID</title>
  <%= stylesheet_link_tag 'layout' %>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= csrf_meta_tag %>
  <!-- Yandex.Metrika -->
  <div style="display:none;"><script type="text/javascript">
  (function(w, c) {
  (w[c] = w[c] || []).push(function() {
  try {
  w.yaCounter2054659 = new Ya.Metrika(2054659);
  yaCounter2054659.clickmap(true);
  yaCounter2054659.trackLinks(true);

  } catch(e) {}
  });
  })(window, 'yandex_metrika_callbacks');
  </script></div>
  <script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript" defer="defer"></script>
  <noscript><div style="position:absolute"><img src="//mc.yandex.ru/watch/2054659" alt="" /></div></noscript>
  <!-- /Yandex.Metrika --> 
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-19905292-1']);
    _gaq.push(['_trackPageview']);

    (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>
<body>
<table>
  <tr>
    <td>
      <%= link_to image_tag('logo.gif'), '/' %> 
    </td>
    <td style="width:150px;text-align:right;">
      <h1>Tovar<font color="red">ID</font></h1>
    </td>
  </tr>
</table>
<% if controller.controller_name == 'products' %> 
  <%= render :partial => 'layouts/products' %>
<% else %>
  <%= yield %>
<% end %>
</body>
</html>

app/views/layouts/points.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TovarID</title>
  <%= stylesheet_link_tag 'layout' %>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= csrf_meta_tag %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Адрес<br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit 'Сохранить' %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Редактирование адреса</h1>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<h1>Рекламные адреса</h1>
<%= link_to 'Сортировать', :sort => 'true' %>
<table>
  <tr>
    <th>Адрес</th>
    <th>Кол-во сканирований</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @points.each do |point| %>
  <tr>
    <td><%= point.address %></td>
    <td><%= point.visit_number %></td>
    <td><%= link_to 'QR код', point.qr_url, :target => "_blank"%></td> 
    <td><%= link_to 'Редактировать', edit_point_path(point) %></td>
    <td><%= link_to '[x]', point, :confirm => 'Вы уверены?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Добавить адрес', new_point_path %>

app/views/points/new.html.erb
<h1>New point</h1>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @point.address %>
</p>

<p>
  <b>Visit number:</b>
  <%= @point.visit_number %>
</p>


<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %>

app/views/points/visit.html.erb
<% if @point %>
  <%= rand(10000) %>
<% else %>
  Такой записи не существует
<% end%>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Список продуктiв</h1>

<table>
  <tr align="left">
    <th>Ім'я</th>
    <th>Опис</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr valign="top">
    <td style="width:50px;"><%= product.name %></td>
    <td style="width:200px;"><%= product.description %></td>
    <td><%= link_to 'Показати', product %><br/>
    <%= link_to 'Редагувати', edit_product_path(product) %><br/>
    <%= link_to 'Видалити', product, :confirm => 'Are you sure?', :method => :delete %><br/>
    <%= link_to 'Сгенерувати код', :action => :new_code, :id => product.id %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Додати продукт', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/new_code.html.erb
<style type="text/css">
 table {
  border-width: 0;
  border-style: none;
  border-color: #0000ff;
  border-collapse: collapse;
 }
 td {
   border-width: 0;
   border-style: none;
   border-color: #0000ff;
   border-collapse: collapse;
   padding: 0;
   margin: 0;
   width: <%= @cell_size %>px;
   height: <%= @cell_size %>px;
 }
 td.black { background-color: #000; }
 td.white { background-color: #fff; }
</style>
<div>
  <%= form_tag(:action => :new_code, :id => params[:id]) do%>
    <table>
      <tr>
        <td style="width:100px">
    Розмiр точки
    </td><td>
    <%= select_tag "cell_size", raw(@cell_sizes.map {|e| "<option #{'selected' if @cell_size == e} value='#{e}'>#{e}</option>" }.join) %>
  </td>
</tr>
<tr><td>
    Розмiр коду
    </td><td>
    <%= select_tag "code_size", raw(@code_sizes.map {|e| "<option #{'selected' if @code_size == e} value='#{e}'>#{e}</option>" }.join) %>
  </td>
</tr>
</table><br/>
    <%= submit_tag 'Сгенерувати код'%>
  <% end %>
</div>
<br/><br/>
<table>
 <% @qr.modules.each_index do |x| -%>
   <tr>
   <% @qr.modules.each_index do |y| -%>
    <% if @qr.is_dark(x,y) -%>
    <td class="black"/>
    <% else -%>
    <td class="white"/>
    <% end -%>
   <% end -%>
   </tr>
 <% end -%>
</table>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/view.html.erb
<% if @product %>
  <div><h3>
      <%= image_tag 'small/accept.png' %>
      Продукт дійсний.
  </h3></div>
  <h5>
  <div> <%= @product.name %></div>
  <div> <%=raw @product.description.gsub(/\r/, '<br />') %> </div>
</h5>
<% else %>
  <%= image_tag 'small/block.png' %>
  Продукт підробний.<br/>
  Зателефонуйте за номером ххх
<% end %>